// Generated by tools/build.mjs. Do not edit by hand.
// Caches the whole app so it keeps working offline once installed.
const VERSION = '4e41f0409979';
const CACHE = 'lintel-' + VERSION;
const PRECACHE = [
  "./",
  "./css/app.css",
  "./fonts/Barlow-400.woff2",
  "./fonts/Barlow-500.woff2",
  "./fonts/Barlow-600.woff2",
  "./fonts/BarlowSemiCondensed-500.woff2",
  "./fonts/BarlowSemiCondensed-600.woff2",
  "./fonts/JetBrainsMono.woff2",
  "./fonts/fonts.css",
  "./icons/apple-touch-icon.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon.svg",
  "./icons/maskable-512.png",
  "./icons/maskable.svg",
  "./index.html",
  "./js/app.js",
  "./js/commands.js",
  "./js/core/derived.js",
  "./js/core/emitter.js",
  "./js/core/model.js",
  "./js/core/ops.js",
  "./js/core/sample.js",
  "./js/core/storage.js",
  "./js/core/units.js",
  "./js/core/vec.js",
  "./js/geom/joins.js",
  "./js/geom/path.js",
  "./js/geom/polygon.js",
  "./js/geom/roof.js",
  "./js/geom/rooms.js",
  "./js/geom/skeleton.js",
  "./js/geom/sketch.js",
  "./js/io/export.js",
  "./js/main.js",
  "./js/plan/hittest.js",
  "./js/plan/planview.js",
  "./js/plan/render.js",
  "./js/plan/snap.js",
  "./js/plan/theme.js",
  "./js/plan/tools/annotate.js",
  "./js/plan/tools/base.js",
  "./js/plan/tools/modify.js",
  "./js/plan/tools/opening.js",
  "./js/plan/tools/roof.js",
  "./js/plan/tools/select.js",
  "./js/plan/tools/sketch.js",
  "./js/plan/tools/wall.js",
  "./js/plan/viewport.js",
  "./js/three/build.js",
  "./js/three/controls.js",
  "./js/three/geo.js",
  "./js/three/lib.js",
  "./js/three/materials.js",
  "./js/three/view3d.js",
  "./js/ui/dialogs.js",
  "./js/ui/form.js",
  "./js/ui/icons.js",
  "./js/ui/props.js",
  "./js/ui/ui.js",
  "./js/ui/views.js",
  "./manifest.webmanifest",
  "./vendor/three.module.min.js"
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('lintel-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    // Network first for the page so updates arrive; cached copy when offline.
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put('./index.html', copy));
          return res;
        })
        .catch(() => caches.match('./index.html')),
    );
    return;
  }
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        }),
    ),
  );
});
