#!/usr/bin/env node
// Build helper.
//
//   node tools/build.mjs            regenerate sw.js and the single-file builds in dist/
//   node tools/build.mjs --vendor   also rebuild vendor/three.module.min.js from node_modules
//
// The app itself needs no build step: index.html loads the ES modules directly.
// dist/lintel.html is a self-contained copy that runs offline from a single file.

import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, existsSync } from 'node:fs';
import { join, relative, dirname } from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const args = new Set(process.argv.slice(2));
const THREE_VERSION = '0.186.1';

async function loadEsbuild() {
  try {
    return await import('esbuild');
  } catch {
    console.error('esbuild is not installed. Run "npm install" first.');
    process.exit(1);
  }
}

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else out.push(p);
  }
  return out;
}

async function buildVendor(esbuild) {
  const entry = join(ROOT, 'tools', '.three-entry.js');
  writeFileSync(entry, "export * from 'three';\nexport { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter.js';\n");
  await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    format: 'esm',
    minify: true,
    legalComments: 'inline',
    outfile: join(ROOT, 'vendor', 'three.module.min.js'),
    logLevel: 'info',
  });
}

function buildServiceWorker() {
  const files = [
    'index.html',
    'manifest.webmanifest',
    ...['css', 'fonts', 'icons', 'js', 'vendor'].flatMap((d) => walk(join(ROOT, d)).map((p) => relative(ROOT, p))),
  ]
    .map((p) => p.split('\\').join('/'))
    .filter((p) => !/\.(txt|md)$/i.test(p))
    .sort();
  const hash = createHash('sha256');
  for (const f of files) hash.update(f).update(readFileSync(join(ROOT, f)));
  const version = hash.digest('hex').slice(0, 12);
  const list = ['./', ...files.map((f) => `./${f}`)];
  const sw = `// Generated by tools/build.mjs. Do not edit by hand.
// Caches the whole app so it keeps working offline once installed.
const VERSION = '${version}';
const CACHE = 'lintel-' + VERSION;
const PRECACHE = ${JSON.stringify(list, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('lintel-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (req.mode === 'navigate') {
    // Network first for the page so updates arrive; cached copy when offline.
    event.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put('./index.html', copy));
          return res;
        })
        .catch(() => caches.match('./index.html')),
    );
    return;
  }
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then(
      (hit) =>
        hit ||
        fetch(req).then((res) => {
          if (res.ok) {
            const copy = res.clone();
            caches.open(CACHE).then((c) => c.put(req, copy));
          }
          return res;
        }),
    ),
  );
});
`;
  writeFileSync(join(ROOT, 'sw.js'), sw);
  console.log(`sw.js: ${list.length} files, version ${version}`);
}

function fontCss() {
  let css = readFileSync(join(ROOT, 'fonts', 'fonts.css'), 'utf8');
  css = css.replace(/url\('([^']+\.woff2)'\)/g, (m, f) => {
    const data = readFileSync(join(ROOT, 'fonts', f)).toString('base64');
    return `url(data:font/woff2;base64,${data})`;
  });
  return css;
}

const SPLASH = '<div id="root"><div class="splash" role="status"><strong>LINTEL</strong><span>Unrolling the drawing board…</span></div></div>';

async function bundleApp(esbuild, { cdnThree = false } = {}) {
  const plugins = [];
  if (cdnThree) {
    plugins.push({
      name: 'three-cdn',
      setup(build) {
        build.onResolve({ filter: /^\.\/lib\.js$/ }, (a) =>
          /[\\/]js[\\/]three[\\/]/.test(a.importer) ? { path: 'three-lib', namespace: 'virtual' } : undefined,
        );
        build.onLoad({ filter: /^three-lib$/, namespace: 'virtual' }, () => ({
          contents: "export * from 'three';\nexport { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';\n",
          loader: 'js',
        }));
        build.onResolve({ filter: /^three(\/.*)?$/ }, (a) => ({ path: a.path, external: true }));
      },
    });
  }
  const res = await esbuild.build({
    entryPoints: [join(ROOT, 'js', 'main.js')],
    bundle: true,
    format: 'esm',
    minify: true,
    write: false,
    legalComments: 'inline',
    target: ['chrome100', 'safari15', 'firefox100'],
    plugins,
  });
  return res.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
}

async function buildStandalone(esbuild) {
  mkdirSync(join(ROOT, 'dist'), { recursive: true });
  const css = fontCss() + '\n' + readFileSync(join(ROOT, 'css', 'app.css'), 'utf8');
  const js = await bundleApp(esbuild);
  const icon = readFileSync(join(ROOT, 'icons', 'icon.svg')).toString('base64');
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover">
<title>Lintel Plan Studio</title>
<meta name="theme-color" content="#123d73">
<link rel="icon" href="data:image/svg+xml;base64,${icon}">
<style>${css}</style>
</head>
<body>
${SPLASH}
<script>window.__LINTEL_NO_SW__ = true;</script>
<script type="module">${js}</script>
</body>
</html>
`;
  writeFileSync(join(ROOT, 'dist', 'lintel.html'), html);
  console.log(`dist/lintel.html: ${(html.length / 1024).toFixed(0)} KB`);
}

/** Page content for a claude.ai artifact (no html/head/body; three.js from jsDelivr). */
async function buildArtifact(esbuild) {
  mkdirSync(join(ROOT, 'dist'), { recursive: true });
  const css = fontCss() + '\n' + readFileSync(join(ROOT, 'css', 'app.css'), 'utf8');
  const js = await bundleApp(esbuild, { cdnThree: true });
  const importMap = {
    imports: {
      three: `https://cdn.jsdelivr.net/npm/three@${THREE_VERSION}/build/three.module.js`,
      'three/addons/': `https://cdn.jsdelivr.net/npm/three@${THREE_VERSION}/examples/jsm/`,
    },
  };
  const page = `<title>Lintel Plan Studio</title>
<style>${css}</style>
${SPLASH}
<script>window.__LINTEL_NO_SW__ = true;</script>
<script type="importmap">${JSON.stringify(importMap)}</script>
<script type="module">${js}</script>
`;
  writeFileSync(join(ROOT, 'dist', 'artifact.html'), page);
  console.log(`dist/artifact.html: ${(page.length / 1024).toFixed(0)} KB`);
}

const esbuild = await loadEsbuild();
if (args.has('--vendor')) await buildVendor(esbuild);
buildServiceWorker();
await buildStandalone(esbuild);
if (args.has('--artifact') || existsSync(join(ROOT, 'dist', 'artifact.html'))) await buildArtifact(esbuild);
